name: Build

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 2

      - uses: actions/setup-node@v5
        with:
          node-version: 22.14.0
          package-manager-cache: false

      - name: Verify Change Logs
        run: node common/scripts/install-run-rush.js change --verify

      - name: Rush Install
        run: node common/scripts/install-run-rush.js install

      - name: Rush rebuild
        run: node common/scripts/install-run-rush.js build:prod --verbose

      - name: Rush extract
        run: node common/scripts/install-run-rush.js extract

      - name: Copy resources
        run: |
          # Online installer
          mkdir dist/docs-install/resources
          cp dist/loader/yascml.js dist/docs-install/resources/yascml.js
          cp dist/manager/yascmanager.zip dist/docs-install/resources/yascmanager.zip
          cp dist/hook/yaschook.zip dist/docs-install/resources/yaschook.zip
          cp dist/sc2ml-compat/sc2ml-compat.zip dist/docs-install/resources/sc2ml-compat.zip
          # Nightly userscript
          cp dist/userscript/yascml.user.js dist/docs/yascml.user.js

      - uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist
  
  docs:
    runs-on: ubuntu-latest
    needs: build
    # TODO: Only deploy when release
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: 'docs'
      cancel-in-progress: false
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: build-artifact
          path: artifact

      - name: Move homepage files
        run: mv artifact/docs dist

      - name: Copy installer
        run: |
          cp -r artifact/docs-install dist/
          mv dist/docs-install dist/install

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PACKAGES_REG_TOKEN }}
          publish_dir: ./dist
          external_repository: yascml/yascml.github.io
          publish_branch: main
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'